from typing import Callable, Iterable, Tuple, List

from . import compute

def expand_as_base(b: int, exp_scalars: Iterable[Tuple[int, int]]) -> str:
    '''
    A UI wrapper for `as_base`

    :param b: The base
    :type b: int
    :param exp_scalars: Exponent-scalar tuples generated by `as_base`
    :type exp_scalars: Iterable[Tuple[int, int]]
    :return: The number represented as a sum of its base `b` digits
    :rtype: str
    '''
    out: List[str] = []
    for i, s in exp_scalars:
        if s != 0:
            out.append(str(s) if i == 0 else f'{s}\xb7{b}{compute.as_exponent(i)}')
    return '0' if len(out) < 1 else ' + '.join(out).replace('+ -', '- ')

def get_int(
    quit_key: int,
    condition: Callable[[int], bool],
    msg: str,
    err_msg: str
) -> int:
    # TODO Document get_int
    while True:
        tmp_num = input(msg).lower().strip()
        if ord(tmp_num[0]) == quit_key:
            exit()
        try:
            num = int(tmp_num)
            if condition(num):
                return num
        except ValueError:
            pass
        print(err_msg)
