from typing import Callable, Iterable, Optional

from . import compute

def expand_as_base(b: int, exp_scalars: Iterable[tuple[int, int]]) -> str:
    '''
    A UI wrapper for `compute.as_base`

    :param b: The base
    :type b: int
    :param exp_scalars: Exponent-scalar tuples generated by `as_base`
    :type exp_scalars: Iterable[tuple[int, int]]
    :return: The number represented as a sum of its base `b` digits
    :rtype: str
    '''
    out: list[str] = []
    for i, s in exp_scalars:
        if s != 0:
            out.append(str(s) if i == 0 else f'{s}\xb7{b}{compute.as_exponent(i)}')
    return '0' if len(out) < 1 else ' + '.join(out).replace('+ -', '- ')

def get_int(
    condition: Callable[[int], bool],
    msg: str = '',
    err_msg: str = '',
    exit_phrase: Optional[str] = None,
) -> Optional[int]:
    '''
    Prompts the user to input an integer satisfying the given condition.

    :param condition: Description. ValueError is treated as failure.
    :type condition: Callable[[int], bool]
    :param msg: The input prompt
    :type msg: str
    :param err_msg: The error message when invalid input is received
    :type err_msg: str
    :param exit_phrase: The phrase to enter to abort this process
    :type exit_phrase: Optional[str]
    :return: Returns None if the exit phrase is entered, otherwise int
    :rtype: Optional[int]
    '''
    while True:
        try:
            tmp_num = input(msg).strip()
        except EOFError:
            return None
        if tmp_num == exit_phrase:
            return None
        try:
            num = int(tmp_num)
            if condition(num):
                return num
        except ValueError:
            pass
        if err_msg:
            print(err_msg)
